	<script lang="ts">
	import Icon from '$lib/ui/Icon.svelte';
	import { page } from '$app/state';

	type Framework = { id: string; name: string; owner: string; purpose: string; structure: string; source: string; sections: { name: string; detail: string; prompt: string }[] };
	const frameworks: Framework[] = [
		{ id: 'nist', name: 'NIST CSF 2.0', owner: 'US National Institute of Standards and Technology', purpose: 'A flexible outcome-based framework for managing cybersecurity risk across organisations of any size.', structure: 'The Core is organised into six Functions, with Categories and Subcategories describing outcomes. Profiles and Tiers help tailor and prioritise the work.', source: 'https://www.nist.gov/cyberframework', sections: [
			{ name: 'Govern', detail: 'Establish cybersecurity strategy, roles, policy, oversight, supply-chain expectations and risk appetite.', prompt: 'Who owns the decision, what is the risk appetite, and what authority is needed?' },
			{ name: 'Identify', detail: 'Understand assets, dependencies, business context, risks and opportunities for improvement.', prompt: 'What is affected, what is critical, and what evidence supports the risk picture?' },
			{ name: 'Protect', detail: 'Put safeguards around identities, access, awareness, data, platforms and technology infrastructure.', prompt: 'Which proportionate controls reduce likelihood or limit blast radius?' },
			{ name: 'Detect', detail: 'Monitor systems and analyse anomalies, indicators and adverse events.', prompt: 'What signal would confirm the threat and who reviews it?' },
			{ name: 'Respond', detail: 'Manage incidents through analysis, reporting, communications, containment and mitigation.', prompt: 'What must happen now, who must be told, and what trade-off is acceptable?' },
			{ name: 'Recover', detail: 'Restore capabilities, communicate recovery status and improve from lessons learned.', prompt: 'What is the safe recovery path and how will readiness be demonstrated?' }
		] },
		{ id: 'caf', name: 'NCSC Cyber Assessment Framework 4.0', owner: 'UK National Cyber Security Centre', purpose: 'An outcome-focused framework for assessing cyber resilience, especially the security of essential functions.', structure: 'CAF has four high-level objectives and fourteen principles. It uses Indicators of Good Practice and expert judgement; it is not intended as a tick-box checklist.', source: 'https://www.ncsc.gov.uk/files/NCSC-Cyber-Assessment-Framework-4.0.pdf', sections: [
			{ name: 'A · Managing security risk', detail: 'Governance, risk management, asset management and supply-chain security.', prompt: 'Which essential function is at risk, and how are ownership, dependencies and supply-chain exposure understood?' },
			{ name: 'B · Protecting against cyber attack', detail: 'Service protection policies, identity and access, data, systems, resilient networks and staff awareness.', prompt: 'Which protection outcome should already be in place, and what gap makes the attack possible?' },
			{ name: 'C · Detecting cyber security events', detail: 'Security monitoring and threat hunting provide timely awareness of events and incidents.', prompt: 'What telemetry, monitoring coverage or hunt would detect this activity in time?' },
			{ name: 'D · Minimising incident impact', detail: 'Response and recovery planning plus lessons learned minimise impact and restore essential functions.', prompt: 'How will continuity be maintained, and what learning must be captured after the exercise?' }
		] },
		{ id: 'cis', name: 'CIS Controls v8.1', owner: 'Center for Internet Security', purpose: 'A prioritised, practical set of safeguards for improving cyber defence and measuring implementation progress.', structure: 'The framework contains 18 Controls and associated Safeguards. Implementation Groups (IG1–IG3) help organisations sequence adoption by risk and resources.', source: 'https://www.cisecurity.org/controls/v8', sections: [
			{ name: 'Know the environment', detail: 'Controls 1–3 cover enterprise assets, software assets and data protection.', prompt: 'Which asset, software dependency or data set is involved, and do we have an accurate inventory?' },
			{ name: 'Harden access and systems', detail: 'Controls 4–7 cover secure configuration, accounts, access control and vulnerability management.', prompt: 'Which weakness or excessive privilege creates the most immediate exposure?' },
			{ name: 'Observe and defend', detail: 'Controls 8–13 cover audit logs, email/web protection, malware defence, recovery, network management and monitoring.', prompt: 'Which safeguard would improve detection, containment or recoverability fastest?' },
			{ name: 'Build resilience', detail: 'Controls 14–18 cover awareness, service providers, application security, incident response and penetration testing.', prompt: 'Which capability, supplier or response process must be tested and evidenced?' }
		] },
		{ id: 'attack', name: 'MITRE ATT&CK Enterprise', owner: 'MITRE', purpose: 'A knowledge base for describing adversary tactics and techniques, useful for threat-informed scenarios and detection engineering.', structure: 'Tactics describe why an adversary acts; techniques and sub-techniques describe how. ATT&CK is not a control framework or a maturity score.', source: 'https://attack.mitre.org/tactics/', sections: [
			{ name: 'Reconnaissance → Initial Access', detail: 'Adversaries gather information, prepare resources and gain an entry point.', prompt: 'What is the likely attack path, initial access technique and early warning signal?' },
			{ name: 'Execution → Credential Access', detail: 'Adversaries run code, persist, escalate privilege, evade defences and obtain credentials.', prompt: 'Which technique is represented, and what containment decision breaks the chain?' },
			{ name: 'Discovery → Collection', detail: 'Adversaries learn the environment, move laterally and gather information of value.', prompt: 'What should defenders know about scope, lateral movement and data exposure?' },
			{ name: 'Command and Control → Impact', detail: 'Adversaries communicate, exfiltrate data and disrupt or damage systems.', prompt: 'What evidence proves impact, and which response action limits operational harm?' }
		] },
		{ id: 'iso', name: 'ISO/IEC 27001:2022', owner: 'International Organization for Standardization', purpose: 'A requirements standard for establishing, implementing, maintaining and continually improving an information security management system (ISMS).', structure: 'Clauses 4–10 describe the ISMS management requirements. Annex A provides a reference set of information security controls grouped into organisational, people, physical and technological themes.', source: 'https://www.iso.org/standard/27001.html', sections: [
			{ name: 'Context and leadership', detail: 'Understand interested parties and scope, establish leadership commitment, policy and accountability.', prompt: 'What business context, leadership decision and ISMS responsibility are relevant?' },
			{ name: 'Planning and support', detail: 'Assess risk, set objectives, provide resources, competence, awareness and controlled information.', prompt: 'What risk treatment, evidence and communication are needed?' },
			{ name: 'Operation and evaluation', detail: 'Operate risk treatments, monitor performance, audit the ISMS and conduct management review.', prompt: 'How will the organisation know the response is effective?' },
			{ name: 'Improvement', detail: 'Handle nonconformities and continually improve suitability, adequacy and effectiveness.', prompt: 'What corrective action, owner and follow-up evidence should result?' }
		] }
	];
	let query = $state('');
	let selected = $derived(page.url.searchParams.get('framework') ?? 'nist');
	let active = $derived(frameworks.find((framework) => framework.id === selected) ?? frameworks[0]);
	let filtered = $derived(active.sections.filter((section) => `${section.name} ${section.detail} ${section.prompt}`.toLowerCase().includes(query.trim().toLowerCase())));
</script>

<svelte:head><title>Framework reference guide · CyberAsk</title><meta name="description" content="A navigable reference guide for cybersecurity exercise alignment frameworks." /></svelte:head>
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-10">
	<div class="rounded-3xl bg-slate-950 p-6 text-white shadow-xl sm:p-9"><div class="max-w-3xl"><p class="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">Reference library</p><h1 class="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Frameworks that turn scenarios into evidence</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Use this guide to brief facilitators, align scenario decisions and give players a shared language. Framework mappings are prompts for better discussion, not certification claims.</p></div><div class="mt-6 flex max-w-xl items-center gap-3 rounded-2xl border border-white/10 bg-white/10 px-4 py-3"><Icon name="search" size={18} /><input bind:value={query} class="w-full bg-transparent text-sm outline-none placeholder:text-slate-400" placeholder="Search outcomes, controls or prompts" aria-label="Search framework guide" /></div></div>
	<div class="mt-6 grid gap-6 lg:grid-cols-[270px_1fr]"><aside class="h-fit rounded-2xl border border-slate-200 bg-white p-2 shadow-sm" aria-label="Frameworks">{#each frameworks as framework}<a href={`/frameworks?framework=${framework.id}`} aria-current={selected === framework.id ? 'page' : undefined} class={`block w-full rounded-xl p-4 text-left transition ${selected === framework.id ? 'bg-teal-50 text-teal-800 ring-1 ring-teal-200' : 'text-slate-600 hover:bg-slate-50'}`}><p class="text-sm font-bold">{framework.name}</p><p class="mt-1 text-xs opacity-70">{framework.owner}</p></a>{/each}<div class="m-2 mt-3 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Tip: map each major decision or inject to an outcome, then use the debrief to capture evidence and improvement actions.</div></aside>
		<main class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-teal-700">{active.owner}</p><h2 class="mt-2 text-2xl font-black text-slate-950">{active.name}</h2><p class="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{active.purpose}</p></div><a class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:border-teal-300 hover:text-teal-700" href={active.source} target="_blank" rel="noreferrer">Official source <Icon name="arrow-right" size={14} /></a></div><div class="mt-6 rounded-2xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">How it is organised</p><p class="mt-2 text-sm leading-6 text-slate-600">{active.structure}</p></div><div class="mt-7 grid gap-3">{#each filtered as section, index}<article class="rounded-2xl border border-slate-200 p-5"><div class="flex gap-4"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-50 text-xs font-black text-teal-700">{index + 1}</span><div><h3 class="font-bold text-slate-900">{section.name}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{section.detail}</p><div class="mt-3 rounded-xl border-l-2 border-teal-400 bg-teal-50/60 px-4 py-3 text-sm text-teal-900"><span class="font-bold">Scenario alignment prompt:</span> {section.prompt}</div></div></div></article>{:else}<p class="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No matching outcomes in this framework.</p>{/each}</div><p class="mt-6 text-xs leading-5 text-slate-400">Always check the current official publication and any sector-specific guidance before making compliance or assurance decisions.</p></main>
	</div>
</div>
