<script lang="ts">
	import type { ReferenceDocument } from '$lib/quiz_types';
	import SlideOutPanel from '$lib/ui/SlideOutPanel.svelte';
	import Icon from '$lib/ui/Icon.svelte';
	interface Props { documents?: ReferenceDocument[]; spotlight?: ReferenceDocument | null; open?: boolean; }
	let { documents = [], spotlight = null, open = $bindable(false) }: Props = $props();
	let selected = $state<ReferenceDocument | null>(null);
	let document_text = $state('');
	let search = $state('');
	let loading = $state(false);
	const document_url = (id: string) => `/api/v1/storage/download/${encodeURIComponent(id)}`;
	const is_text = (document: ReferenceDocument) => ['text/plain', 'text/markdown'].includes(document.mime_type ?? '') || /\.(txt|md)$/i.test(document.filename ?? '');
	const matches = $derived(search.trim() ? document_text.split('\n').map((text, index) => ({ text, index })).filter((line) => line.text.toLowerCase().includes(search.trim().toLowerCase())) : []);
	const open_document = async (document: ReferenceDocument) => { selected = document; search = ''; document_text = ''; if (!is_text(document)) return; loading = true; try { const response = await fetch(document_url(document.id)); if (response.ok) document_text = await response.text(); } finally { loading = false; } };
	$effect(() => { if (spotlight) { open = true; void open_document(spotlight); } });
</script>
<SlideOutPanel bind:open title="Reference shelf" description="Company policies and framework references supplied for this exercise." width="max-w-xl">
	<div class="space-y-5"><div class="rounded-2xl border border-teal-100 bg-teal-50 p-4 text-sm text-teal-900"><p class="font-semibold">Use the shelf to ground decisions</p><p class="mt-1 text-xs leading-5 text-teal-800">These documents are exercise references, not a substitute for current legal, regulatory, or professional advice.</p></div>
		{#if selected}<div class="space-y-4"><div class="flex items-center justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-bold text-slate-900">{selected.title}</p><p class="text-xs text-slate-500">{selected.filename ?? 'Reference document'}</p></div><button type="button" class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:border-teal-300 hover:text-teal-700" onclick={() => (selected = null)}>Back to shelf</button></div>
			{#if is_text(selected)}<label class="block"><span class="mb-1 block text-xs font-bold uppercase tracking-wider text-slate-400">Search this policy</span><div class="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2"><Icon name="search" size={16} /><input bind:value={search} class="w-full text-sm outline-none" placeholder="Search words or phrases" aria-label="Search policy text" /></div></label>{#if loading}<p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Loading policy text…</p>{:else if search && matches.length}<p class="text-xs font-semibold text-teal-700">{matches.length} matching line{matches.length === 1 ? '' : 's'}</p>{:else if search}<p class="text-xs text-slate-500">No matching text found.</p>{/if}<div class="max-h-[55vh] overflow-auto rounded-2xl border border-slate-200 bg-slate-50 p-4"><pre class="whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{#if search && matches.length}{#each matches as match}<span class="block rounded-lg bg-yellow-100 px-2 py-1">{match.text}</span>{/each}{:else}{document_text || 'This document has no readable text.'}{/if}</pre></div>
			{:else if selected.mime_type === 'application/pdf'}<iframe title={`Preview of ${selected.title}`} src={document_url(selected.id)} class="h-[65vh] w-full rounded-2xl border border-slate-200"></iframe>
			{:else}<div class="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><p class="text-sm font-semibold text-slate-700">This document is ready to open</p><p class="mt-1 text-xs text-slate-500">DOCX files open in a new browser tab. Text search is available for TXT and Markdown policies.</p><a class="mt-4 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-xs font-bold text-white" href={document_url(selected.id)} target="_blank" rel="noreferrer">Open document <Icon name="arrow-right" size={14} /></a></div>{/if}</div>
		{:else if documents.length}<div class="space-y-3">{#each documents as document}<button type="button" onclick={() => open_document(document)} class="flex w-full items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:border-teal-300 hover:bg-teal-50"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-teal-700"><Icon name="file" size={18} /></span><span class="min-w-0"><span class="block truncate text-sm font-bold text-slate-900">{document.title}</span><span class="mt-1 block text-xs font-semibold uppercase tracking-wider text-teal-700">{document.category ?? 'Company reference'}</span>{#if document.description}<span class="mt-1 block text-xs leading-5 text-slate-500">{document.description}</span>{/if}<span class="mt-2 block text-xs text-slate-400">{document.filename ?? 'Open document'} · Open in exercise viewer</span></span></button>{/each}</div>
		{:else}<div class="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center text-sm text-slate-500">No company references were supplied for this exercise.</div>{/if}
		<a href="/frameworks" class="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4 text-sm font-bold text-slate-700 transition hover:border-teal-300 hover:text-teal-700"><span>Browse framework reference library</span><Icon name="arrow-right" size={16} /></a></div>
</SlideOutPanel>
