# SPDX-FileCopyrightText: 2026 CyberAsk
# SPDX-License-Identifier: MPL-2.0

from classquiz.seed.builders import abcd_q, base_quiz, file_q, info_q, voting_q


def build() -> dict:
    injects = [
        {"id": "ci-inj-1", "title": "MFA fatigue alert", "content": "**SOC:** {{ciso_name}} receives 38 push approvals in seven minutes from an unfamiliar location.", "severity": "warning", "trigger_after_question_id": "ci-discovery"},
        {"id": "ci-inj-2", "title": "Privileged token replay", "content": "**Cloud:** A session token for the global administrator role is replayed against {{primary_system}}.", "severity": "critical", "trigger_after_question_id": "ci-d1-contain"},
        {"id": "ci-inj-3", "title": "Customer outage", "content": "**Support:** Conditional-access changes have locked out 18% of customers. The status page is attracting attention.", "severity": "warning", "trigger_after_question_id": "ci-d2-access"},
        {"id": "ci-inj-4", "title": "Contractual deadline", "content": "**Legal:** A strategic customer requires a preliminary incident update within four hours under the MSA.", "severity": "info", "trigger_after_question_id": "ci-comms"},
        {"id": "ci-inj-5", "title": "Persistence found", "content": "**Threat hunt:** An OAuth application with mail-read permissions was installed three weeks ago by a compromised user.", "severity": "critical", "trigger_after_question_id": "ci-d3-recover"},
    ]

    questions = [
        info_q("ci-brief", "Exercise Briefing — Cloud Identity Compromise", "<p><strong>{{company_name}}</strong> is investigating a suspected identity compromise spanning its cloud tenant and {{primary_system}}.</p><p>Players will balance containment, customer access, evidence, and recovery.</p>", next_id="ci-context", discussion=180),
        info_q("ci-context", "Identity & Cloud Context", "<p>{{employee_count}} staff use cloud SSO across {{location}}. Privileged access is managed by a small IAM team.</p><p>Critical data includes {{data_classification}} and customer records in {{primary_system}}.</p>", next_id="ci-discovery"),
        info_q("ci-discovery", "Discovery — Suspicious Sign-ins", "<p>Impossible-travel alerts show a privileged user signing in from {{region}} and an anonymising network.</p><p>The user reports repeated MFA prompts but cannot confirm approving one.</p>", next_id="ci-evidence", discussion=180),
        file_q("ci-evidence", "Evidence Review — Identity Audit Trail", "<p>Review sign-in, OAuth consent, and conditional-access evidence. Identify the likely persistence mechanism.</p>", "cloud-identity-audit.txt", "Synthetic cloud audit export containing sign-ins, token use, and OAuth consent events.", next_id="ci-d1-contain", roles=["SOC Lead", "IAM Lead"], discussion=240),
        abcd_q("ci-d1-contain", "Decision 1 — Contain the compromised identity", "What is your first containment action?", [("Revoke sessions, disable the account, and preserve audit evidence", "ci-d2-access"), ("Force a password reset and monitor for another sign-in", "ci-d2-monitor"), ("Block the source network and leave the account active", "ci-d2-monitor"), ("Wait for legal approval before changing access", "ci-d2-crisis")], roles=["Incident Commander", "IAM Lead", "SOC Lead"], objective="Containment", sla=[{"deadline_seconds": 300, "bonus_points": 40, "penalty_points": 20, "description": "Containment decision within 5 minutes"}]),
        abcd_q("ci-d2-access", "Branch — Access control response", "How broadly do you apply emergency access controls?", [("Require phishing-resistant MFA for privileged roles and rotate sessions", "ci-d3-recover"), ("Lock down the entire tenant for certainty", "ci-d2-crisis"), ("Protect only production subscriptions", "ci-comms"), ("Remove all third-party OAuth applications immediately", "ci-d3-recover")], roles=["IAM Lead", "Cloud Platform Owner"], objective="Containment"),
        abcd_q("ci-d2-monitor", "Branch — Monitor-first response", "The suspicious user signs in again through a new IP. What next?", [("Escalate to full identity containment and hunt for persistence", "ci-d3-recover"), ("Block the new IP and continue observing", "ci-comms"), ("Ask the user to confirm activity by email", "ci-d2-crisis"), ("Disable only the original device", "ci-d3-recover")], roles=["SOC Lead", "IAM Lead"], objective="Detection"),
        abcd_q("ci-d2-crisis", "Branch — Business continuity pressure", "Customer access is degrading as emergency controls spread. What is your response?", [("Declare a major incident and activate the continuity plan", "ci-comms"), ("Roll back the controls to protect availability", "ci-comms"), ("Ask the vendor to decide the safest setting", "ci-d3-recover"), ("Pause all changes until the executive team meets", "ci-comms")], roles=["Incident Commander", "Business Continuity Manager"], objective="Communication"),
        abcd_q("ci-comms", "Decision 2 — Customer and stakeholder communication", "What do you communicate while scope is still being assessed?", [("Use a factual holding statement and brief affected customers directly", "ci-d3-recover"), ("Say nothing until every account is reviewed", "ci-d3-recover"), ("Publish technical indicators publicly immediately", "ci-d3-recover"), ("Describe the event as a routine maintenance issue", "ci-d3-recover")], roles=["Communications Lead", "Legal & Compliance"], objective="Communication"),
        abcd_q("ci-d3-recover", "Decision 3 — Recover the tenant", "How do you restore confidence in the identity platform?", [("Remove persistence, rotate privileged secrets, and rebuild trust in stages", "ci-vote"), ("Restore from the last tenant configuration backup", "ci-vote"), ("Rotate all user passwords and close the incident", "ci-vote"), ("Wait for the provider's final forensic report", "ci-vote")], roles=["IAM Lead", "Cloud Platform Owner", "CISO"], objective="Recovery"),
        voting_q("ci-vote", "Identity resilience priorities", "Which remediation investment should be prioritised first?", ["Phishing-resistant MFA for privileged users", "Privileged access management and just-in-time elevation", "OAuth application governance", "Identity detection and response coverage"], next_id="ci-lessons", notes="Use the vote to drive the 30/60/90-day remediation plan."),
        info_q("ci-lessons", "Lessons Learned — Identity Resilience", "<p>Review session revocation, conditional access, OAuth governance, privileged access, and customer communication.</p><p>Assign owners for 30/60/90-day improvements.</p>", next_id="ci-close", objective="Recovery", discussion=300),
        info_q("ci-close", "Exercise Close", "<p>{{company_name}} cloud identity compromise exercise complete.</p>", notes="Summarise the path taken, decision latency, and remediation owners."),
    ]

    return base_quiz(title="{{company_name}} — Cloud Identity Compromise Tabletop", description="Branching cloud identity exercise covering MFA fatigue, session theft, OAuth persistence, emergency access control, customer communication, and recovery.", questions=questions, injects=injects, roles=["Incident Commander", "CISO", "SOC Lead", "IAM Lead", "Cloud Platform Owner", "Legal & Compliance", "Communications Lead", "Business Continuity Manager"])
